config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :carts, only: [:show]
  get "museums/:id/tagging" => "museums#tagging_new"
  post "museums/:id/tagging" => "museums#tagging_create"
  resources :museums
  get "tickets/stats" => "tickets#stats"
  get "tickets/redeem/:id" => "tickets#redeem"
  resources :tickets
  get "exhibits/:id/tagging" => "exhibits#tagging_new"
  post "exhibits/:id/tagging" => "exhibits#tagging_create"
  get "exhibits/search_new" => "exhibits#search_new"
  get "exhibits/search_show" => "exhibits#search_show"
  resources :exhibits
  get "pieces/:id/tagging" => "pieces#tagging_new"
  post "pieces/:id/tagging" => "pieces#tagging_create"
  resources :pieces
  get "events/:id/tagging" => "events#tagging_new"
  post "events/:id/tagging" => "events#tagging_create"
  resources :events
  resources :charges
  get "users/:id/personalized" => "users#personalized"
  get "users/:id/tagging" => "users#tagging_new"
  post "users/:id/tagging" => "users#tagging_create"
  resources :users, only: [:show, :edit, :update]
  resources :taggings
  resources :tags, only: [:show]

  root to: "museums#index"
end

app/models/exhibit.rb
class Exhibit < ApplicationRecord
  belongs_to :museum
  has_many :taggings
  has_many :tickets
  has_many :tags, through: :taggings
  accepts_nested_attributes_for :taggings, :allow_destroy => true

  has_attached_file :photo, styles: { large: "768x768>", medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\Z/
  validates_presence_of :name, :start_date, :end_date, :blurb, :description, :photo
  validates_uniqueness_of :name
end

app/controllers/exhibits_controller.rb
class ExhibitsController < ApplicationController
  before_action :administrative, only: [:new, :create, :edit, :update, :destroy]
  skip_before_filter :verify_authenticity_token, :only => :tagging_create



  def show
    @ticket = current_order.tickets.new
    @exhibit = Exhibit.find(params[:id])
    @museum = Museum.find(@exhibit.museum_id)
  end

  def new
    @exhibit = Exhibit.new
  end

  def create
    @exhibit = Exhibit.new(exhibit_params)
    if @exhibit.save
      redirect_to :root
    else
      @errors = @exhibit.errors.full_messages
      render :"exhibits/new"
    end
  end

  def search_show
    @all_posts = Museum.all + Exhibit.all + Event.all + Piece.all + Tag.all
    @ticket = current_order.tickets.new
    @posts = []
    @term = params[:search].downcase
    if params[:search]
      if params[:tag_search]
        @all_posts.each do |post|
          params[:tag_search].each do |param|
            if post.is_a?(Tag)
              if post.name.downcase.include?(param)
                @posts << post
              end
            elsif (post.name.downcase.include?(@term) && post.tags.any? {|attribute| attribute.name == param}) || (post.description.downcase.include?(@term) &&  post.tags.any? {|attribute| attribute == param})
              @posts << post
            end
          end
        end
        puts params[:tag_search]
      else
        @all_posts.each do |post|
          if post.is_a?(Tag)
            if post.name.downcase.include?(@term)
              @posts << post
            end
          else
            if post.name.downcase.include?(@term) || post.description.downcase.include?(@term)
              @posts << post
            end
          end
        end
      end
    else
      @posts = @all_posts.all.order('created_at DESC')
    end
    @posts = @posts.uniq
  end


  def search_new
    @all_posts = Museum.all + Exhibit.all + Event.all + Piece.all + Tag.all
    @tags = Tag.all
  end
  
  def update
    @exhibit = Exhibit.find(params[:id])
    if @exhibit.update(exhibit_params)
      redirect_to :root
    else
      render :"post/edit"
    end
  end

  def tagging_new
    @exhibit = Exhibit.find(params[:id])
    @tagging = Tagging.new
  end

  def tagging_create
    @exhibit = Exhibit.find(params[:id])
    exhibit_params[:tag_ids].each do |tag|
      if tag != ""
        @tagging = @exhibit.taggings.new(tag_id: tag.to_i)
        @tagging.save
        Rails.logger.info(@tagging.errors.inspect)
      end
    end
    redirect_to exhibit_path(@exhibit)
  end

  def edit
    @exhibit = Exhibit.find(params[:id])
  end

  def destroy
    @exhibit = Exhibit.find(params[:id])
    @exhibit.destroy
    redirect_to :root
  end

  private

  def exhibit_params
    params.require(:exhibit).permit(:name, :blurb, :description, :photo, :start_date, :end_date, :museum_id, :tag_ids => [])
  end
  end

app/helpers/exhibit_helper.rb
module ExhibitHelper
end

app/views/exhibits/_search_row.html.erb
<% if post.is_a?(Museum) %>
  <div class="post-wrapper museum-panel">
<% elsif post.is_a?(Exhibit) %>
  <div class="post-wrapper exhibit-panel">
<% elsif post.is_a?(Event) %>
  <div class="post-wrapper event-panel">
<% elsif post.is_a?(Piece) %>
  <div class="post-wrapper piece-panel">
<% else %>
  <div class="post-wrapper">
<% end %>
  <div class="thumbnail">
    <% unless post.is_a?(Tag) %>
      <%= link_to image_tag(post.photo.url(:large)), post %>
    <% end %>
    <div class="caption">
      <h3><%= link_to "#{post.name}", post %></h3>
      <% unless post.is_a?(Tag) %>
        <p><%= post.blurb %></p>
      <% end %>
      <a>Read More</a>
      <div>
        <% if current_user && post.is_a?(Museum) %>
          <%= form_for ticket, remote: true do |f| %>
            <div class="input-group">
              <div class="input-group-btn">
                <%= f.hidden_field :quantity, value: 1 %>
                <%= f.hidden_field :museum_id, value: post.id %>
                <%= f.hidden_field :user_id, value: current_user.id %>
                <%= f.submit "Purchase Tickets", class: "btn btn-primary" %>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
  <div class="progress">
    <div class="progress-bar progress-bar-striped" style= "width: 100%"></div>
  </div>
</div>

app/views/exhibits/edit.html.erb
<%= form_for (@exhibit), html: {multipart: true} do |f| %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, autofocus: true %>
  </div>

  <div class="field">
    <%= f.label :blurb %>
    <%= f.text_field :blurb %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :start_date %>
    <%= f.date_field :start_date %>
  </div>

  <div class="field">
    <%= f.label :end_date %>
    <%= f.date_field :end_date %>
  </div>

  <div class="field">
    <%= f.label :photo %>
    <%= f.file_field :photo %>
  </div>

  <div class="field">
    <%= f.label :museum_id %>
    <%= f.collection_select :museum_id, Museum.order(:name), :id, :name %>
  </div>

  <div class="actions">
    <%= f.submit "Add Exhibit"%>
  </div>
<% end %>

<% if @exhibit.errors.any? %>
  <% @exhibit.errors.each do |attribute, message| %>
    <%= attribute %>:
    <%= message %>
  <% end %>
<% end %>

app/views/exhibits/new.html.erb
<%= form_for (@exhibit), html: {multipart: true} do |f| %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, autofocus: true %>
  </div>

  <div class="field">
    <%= f.label :blurb %>
    <%= f.text_field :blurb %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :start_date %>
    <%= f.date_field :start_date %>
  </div>

  <div class="field">
    <%= f.label :end_date %>
    <%= f.date_field :end_date %>
  </div>

  <div class="field">
    <%= f.label :photo %>
    <%= f.file_field :photo %>
  </div>

  <div class="field">
    <%= f.label :museum_id %>
    <%= f.collection_select :museum_id, Museum.order(:name), :id, :name %>
  </div>

  <div class="actions">
    <%= f.submit "Add Exhibit"%>
  </div>
<% end %>

<% if @exhibit.errors.any? %>
  <% @exhibit.errors.each do |attribute, message| %>
    <%= attribute %>:
    <%= message %>
  <% end %>
<% end %>

app/views/exhibits/search_new.html.erb
<div id= "search-wrapper">
  <%= form_tag(exhibits_search_show_path, :method => "get", id: "search-form") do %>
    <i class="fa fa-search" aria-hidden="true" style="font-size: 20px"></i>
    <%= text_field_tag :search, params[:search], placeholder: "Search" %>
    <% @tags.each do |tag| %>
    <li class="checkboxtext">
      <%= check_box_tag "tag_search[]", tag.name %>
      <%= tag.name %>
    </li>
    <% end %>
  <% end %>
</div>

app/views/exhibits/search_show.html.erb
<h2>Search Results:</h2>
<div class="row masonry-row">
  <% if @posts.empty? %>
    <p> Sorry! Nothing matches your search query.</p>
  <% else %>
  	<% @posts.shuffle.each do |post| %>
  	  <%= render "search_row", post: post, ticket: @ticket  %>
  	<% end %>
  <% end %>
</div>

app/views/exhibits/show.html.erb
<%= @exhibit.name %><br>
<% @exhibit.tags.each do |tag| %>
  <p><%= link_to "##{tag.name}", tag %></p>
<% end %>
<%= @exhibit.description %>
<p>
  From <%=@exhibit.start_date%> - <%= @exhibit.end_date %>
</p>
<%= link_to "Currently at #{@museum.name}", @museum %>
<br><br>
<%= image_tag @exhibit.photo.url(:large) %>
<%= form_for @ticket, remote: true do |f| %>
  <div class="input-group">
    <div class="input-group-btn">
      <%= f.hidden_field :quantity, value: 1%>
      <%= f.hidden_field :museum_id, value: @exhibit.museum_id %>
      <%= f.hidden_field :exhibit_id, value: @exhibit.id %>
      <%= f.hidden_field :user_id, value: current_user.id %>
      <%= f.submit "Add to Cart", class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

<% if admin? %>
  <%= link_to "Add Exhibit Tags", "#{@exhibit.id}/tagging" %>
  <%= link_to "Edit Exhibit", edit_exhibit_path %>
<% end %>

app/views/exhibits/tagging_new.html.erb
<%= form_for(@exhibit, :url => "tagging", :html => { :method => :post }) do |f| %>

   <p>Tags</p>
   <ul>
     <% Tag.all.each do |tag| %>
     <%= hidden_field_tag "exhibit_tag_ids_none", nil, {:name => "exhibit[tag_ids][]"}%>
     <li>
       <%= check_box_tag "exhibit_tag_ids_#{tag.id}", tag.id, (f.object.taggings.present? && f.object.taggings.include?(tag.id)), {:name => "exhibit[tag_ids][]"} %>
       <%= label_tag "exhibit_tag_ids_#{tag.id}", tag.name %>
     </li>
     <% end %>
   </ul>

   <%= f.submit %>

<% end %>