config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :carts, only: [:show]
  get "museums/:id/tagging" => "museums#tagging_new"
  post "museums/:id/tagging" => "museums#tagging_create"
  resources :museums
  get "tickets/stats" => "tickets#stats"
  get "tickets/redeem/:id" => "tickets#redeem"
  resources :tickets
  get "exhibits/:id/tagging" => "exhibits#tagging_new"
  post "exhibits/:id/tagging" => "exhibits#tagging_create"
  get "exhibits/search_new" => "exhibits#search_new"
  get "exhibits/search_show" => "exhibits#search_show"
  resources :exhibits
  get "pieces/:id/tagging" => "pieces#tagging_new"
  post "pieces/:id/tagging" => "pieces#tagging_create"
  resources :pieces
  get "events/:id/tagging" => "events#tagging_new"
  post "events/:id/tagging" => "events#tagging_create"
  resources :events
  resources :charges
  get "users/:id/personalized" => "users#personalized"
  get "users/:id/tagging" => "users#tagging_new"
  post "users/:id/tagging" => "users#tagging_create"
  resources :users, only: [:show, :edit, :update]
  resources :taggings
  resources :tags, only: [:show]

  root to: "museums#index"
end

app/models/museum.rb
class Museum < ApplicationRecord
  has_many :tickets
  has_many :taggings
  has_many :tags, through: :taggings
  default_scope { where(active: true) }
  accepts_nested_attributes_for :taggings, :allow_destroy => true
  has_many :exhibits
  has_many :events
  has_many :pieces

  has_attached_file :photo, styles: { large: "768x768>", medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\Z/

  validates_presence_of :name, :blurb, :description, :photo, :price, :address
  validates_uniqueness_of :name

  geocoded_by :address
  after_validation :geocode, if: ->(obj){ obj.address.present? and obj.address_changed? }
end

app/controllers/museums_controller.rb
class MuseumsController < ApplicationController
  before_action :administrative, only: [:new, :create, :edit, :update, :destroy]
  skip_before_filter :verify_authenticity_token, :only => :tagging_create

  def index
    @ticket = current_order.tickets.new
    @posts = Museum.all + Exhibit.all + Event.all + Piece.all
  end

  def show
    @museum = Museum.find(params[:id])
    @ticket = current_order.tickets.new
    @exhibits = @museum.exhibits.all
    @hash = Gmaps4rails.build_markers(@museum) do |museum, marker|
     marker.lat museum.latitude
     marker.lng museum.longitude
   end
  end

  def new
    @museum = Museum.new
  end

  def create
    @museum = Museum.new(museum_params)
    if @museum.save
      redirect_to :root
    else
      @errors = @museum.errors.full_messages
      render :"museums/new"
    end
  end

  def update
    @museum = Museum.find(params[:id])
    if @museum.update(museum_params)
      redirect_to :root
    else
      render :"post/edit"
    end
  end

  def tagging_new
    @museum = Museum.find(params[:id])
    @tagging = Tagging.new
  end

  def tagging_create
    @museum = Museum.find(params[:id])
    museum_params[:tag_ids].each do |tag|
      if tag != ""
        @tagging = @museum.taggings.new(tag_id: tag.to_i)
        @tagging.save
        Rails.logger.info(@tagging.errors.inspect)
      end
    end
    redirect_to museum_path(@museum)
  end

  def edit
    @museum = Museum.find(params[:id])
  end

  def destroy
    @museum = Museum.find(params[:id])
    @museum.destroy
    redirect_to :root
  end

  private

  def museum_params
    params.require(:museum).permit(:name, :blurb, :description, :photo, :address, :price, :tag_ids => [])
  end

end

app/helpers/museum_helper.rb
module MuseumHelper
end

app/views/museums/_museum_row.html.erb
<% if post.is_a?(Museum) %>
  <div class="col-sm-6 col-md-4 col-lg-3 post-wrapper museum-panel">
<% elsif post.is_a?(Exhibit) %>
  <div class="col-sm-6 col-md-4 col-lg-3 post-wrapper exhibit-panel">
<% elsif post.is_a?(Event) %>
  <div class="col-sm-6 col-md-4 col-lg-3 post-wrapper event-panel">
<% elsif post.is_a?(Piece) %>
  <div class="col-sm-6 col-md-4 col-lg-3 post-wrapper piece-panel">
<% else %>
  <div class="col-sm-6 col-md-4 col-lg-3 post-wrapper">
<% end %>
  <div class="thumbnail">
    <%= link_to image_tag(post.photo.url(:large)), post %>
    <div class="caption">

      <div class="thumbnail-header">
        <h3><%= link_to "#{post.name}", post %></h3>
        <p> $<%= '%i' % post.price %>
          <% if defined? post.exhibits %>
          - $<%= '%i' %post.exhibits.sort.first.price %>
          <% end %>
      </div>
      <p><%= post.blurb %></p>

      <div>
        <% if current_user && post.is_a?(Museum) %>
          <%= form_for ticket, remote: true do |f| %>
            <div class="input-group">
              <div class="input-group-btn">
                <%= f.hidden_field :quantity, value: 1 %>
                <%= f.hidden_field :museum_id, value: post.id %>
                <%= f.hidden_field :user_id, value: current_user.id %>
                <%= f.submit "Purchase Tickets", class: "btn btn-primary" %>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
  <div class="progress">
    <div class="progress-bar progress-bar-striped" style= "width: 100%"></div>
  </div>
</div>

app/views/museums/edit.html.erb
<%= form_for @museum, html: {multipart: true} do |f| %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, autofocus: true %>
  </div>

  <div class="field">
    <%= f.label :blurb %>
    <%= f.text_field :blurb %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :address %>
    <%= f.text_field :address %>
  </div>

  <div class="field">
    <%= f.label :photo %>
    <%= f.file_field :photo %>
  </div>

  <div class="actions">
    <%= f.submit "Edit Museum"%>
  </div>
<% end %>

<% if @mueseum.errors.any? %>
  <% @mueseum.errors.each do |attribute, message| %>
    <%= attribute %>:
    <%= message %>
  <% end %>
<% end %>

<br>

<%= link_to "Delete Museum", @museum, :method => :delete, :confirm => "You sure?" %>

app/views/museums/index.html.erb
<div class= "row masonry-container">
	<div class= "col-sm-6 col-md-4 col-lg-3 app-advertisement post-wrapper">
		<div class="thumbnail">
		 <%= image_tag("hero.png") %>
			<div class="caption">
				<div class="thumbnail-header">
					<a href="medici-app.com">Mobile App Coming Soon</a>
				</div>
				<p>medici app by cinco technologys &copy is the first mobile app for ordering bike messangers to carry you to the Art exhibits for free all week long call them when ever but dont touch</p>
			</div>
		</div>
		<div class="progress">
			<div class="progress-bar progress-bar-striped" style= "width: 100%"></div>
		</div>
	</div>
	<% @posts.shuffle.each do |post| %>
	  <%= render "museum_row", post: post, ticket: @ticket  %>
	<% end %>
</div>

<div class="admin">
	<% if admin? %>
		<%= link_to "Add Museum", new_museum_path %><br>
		<%= link_to "Add Exhibit", new_exhibit_path %><br>
		<%= link_to "Add Event", new_event_path %><br>
		<%= link_to "Add Piece", new_piece_path %><br>
		<%= link_to "See Backend Numbers", tickets_stats_path %>
	<% end %>
</div>

app/views/museums/new.html.erb
<%= form_for (@museum), html: {multipart: true} do |f| %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, autofocus: true %>
  </div>

  <div class="field">
    <%= f.label :blurb %>
    <%= f.text_field :blurb %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :address %>
    <%= f.text_field :address %>
  </div>

  <div class="field">
    <%= f.label :price %>
    <%= f.number_field :price %>
  </div>

  <div class="field">
    <%= f.label :photo %>
    <%= f.file_field :photo %>
  </div>

  <div class="actions">
    <%= f.submit "Add Museum"%>
  </div>
<% end %>

<% if @museum.errors.any? %>
  <% @museum.errors.each do |attribute, message| %>
    <%= attribute %>:
    <%= message %>
  <% end %>
<% end %>

app/views/museums/show.html.erb
<div class= "container-fluid yourDiv">
  <div class="row myDiv">
    <div class= "col-sm-6 image-wrap">
      <%= image_tag @museum.photo.url(:large), class:"hero-image" %>
    </div>
    <div class= "col-sm-6 myDiv">
      <%= @museum.name %>
      <%= @museum.description %>
    </div>
  </div>
  <div class= "row myDiv">
    <div class="col-sm-4 myDiv"><div id="map">
    </div>
    <p>
      <%= @museum.address %>
    </p>
  </div>
    <div class="col-sm-4 myDiv">moope</div>
    <div class="col-sm-4 myDiv">morp</div>
  </div>
  <div class= "row mydiv">

</div>

  <% if current_user %>
    <%= form_for @ticket, remote: true do |f| %>
      <h4>Unit Price: <%= number_to_currency @museum.price %></span></h4>
      <div class="input-group">
        <div class="input-group-btn">
          <%= f.hidden_field :quantity, value: 1%>
          <%= f.hidden_field :museum_id, value: @museum.id %>
          <%= f.hidden_field :user_id, value: current_user.id %>
          <%= f.submit "Add to Cart", class: "btn btn-primary" %>
        </div>
      </div>
    <% end %>
  <% else %>
    <%= link_to "Sign in to buy tickets!", new_user_session_path %>
  <% end %>
  <% if admin? %>
    <%= link_to "Add Museum Tags", "#{@museum.id}/tagging" %>
    <%= link_to "Edit Museum", edit_museum_path %>
  <% end %>

<h2> Exhibits: </h2>

<% @exhibits.each do |exhibit| %>
  <h3> <%= exhibit.name %> </h3 >
  <p> <%= exhibit.start_date.strftime("%m/%Y/%d %I:%M%p") %> - <%= exhibit.end_date.strftime("%m/%Y/%d %I:%M%p") %> </p>
  <p><%= exhibit.description %></p>
  <%= image_tag exhibit.photo.url(:large) %>
<% end %>

<script type="text/javascript">
  function buildMap(){
    handler = Gmaps.build('Google');
    handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
      markers = handler.addMarkers(<%=raw @hash.to_json %>);
      handler.bounds.extendWith(markers);
      handler.fitMapToBounds();
      handler.getMap().setZoom(12);
    });
  }
  $(window).onload(buildMap())
</script>

app/views/museums/tagging_new.html.erb
<%= form_for(@museum, :url => "tagging", :html => { :method => :post }) do |f| %>

   <p>Tags</p>
   <ul>
     <% Tag.all.each do |tag| %>
     <%= hidden_field_tag "museum_tag_ids_none", nil, {:name => "museum[tag_ids][]"}%>
     <li>
       <%= check_box_tag "museum_tag_ids_#{tag.id}", tag.id, (f.object.taggings.present? && f.object.taggings.include?(tag.id)), {:name => "museum[tag_ids][]"} %>
       <%= label_tag "museum_tag_ids_#{tag.id}", tag.name %>
     </li>
     <% end %>
   </ul>

   <%= f.submit %>

<% end %>