config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :carts, only: [:show]
  get "museums/:id/tagging" => "museums#tagging_new"
  post "museums/:id/tagging" => "museums#tagging_create"
  resources :museums
  get "tickets/stats" => "tickets#stats"
  get "tickets/redeem/:id" => "tickets#redeem"
  resources :tickets
  get "exhibits/:id/tagging" => "exhibits#tagging_new"
  post "exhibits/:id/tagging" => "exhibits#tagging_create"
  get "exhibits/search_new" => "exhibits#search_new"
  get "exhibits/search_show" => "exhibits#search_show"
  resources :exhibits
  get "pieces/:id/tagging" => "pieces#tagging_new"
  post "pieces/:id/tagging" => "pieces#tagging_create"
  resources :pieces
  get "events/:id/tagging" => "events#tagging_new"
  post "events/:id/tagging" => "events#tagging_create"
  resources :events
  resources :charges
  get "users/:id/personalized" => "users#personalized"
  get "users/:id/tagging" => "users#tagging_new"
  post "users/:id/tagging" => "users#tagging_create"
  resources :users, only: [:show, :edit, :update]
  resources :taggings
  resources :tags, only: [:show]

  root to: "museums#index"
end

app/models/charge.rb
class Charge < ApplicationRecord
  belongs_to :coupon
  validates_presence_of :amount, :stripe_id
end

app/models/coupon.rb
class Coupon < ApplicationRecord
  has_many :charges
  validates_presence_of :code, :discount_percent
  validates_uniqueness_of :code

  def self.get(code)
    where(code: normalize_code(code)).
    where('expires_at > ? OR expires_at IS NULL', Time.now).
    take
  end

  def apply_discount(amount)
    discount = amount * (self.discount_percent * 0.01)
    (amount - discount.to_i)
  end

  def discount_percent_human
    if discount_percent.present?
      discount_percent.to_s + "%"
    end
  end

  private

  def self.normalize_code(code)
    code.gsub(/\s+/, '').upcase
  end
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :museum
  has_many :taggings
  has_many :tags, through: :taggings
  accepts_nested_attributes_for :taggings, :allow_destroy => true
  validate :end_must_be_after_start

  has_attached_file :photo, styles: { large: "768x768>", medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\Z/
  validates_presence_of :name, :start_date, :end_date, :blurb, :description, :photo
  validates_uniqueness_of :name

  private
    def end_must_be_after_start
      if start_date >= end_date
        errors.add(:end_date, "must be after start date")
      end
    end
end

app/models/exhibit.rb
class Exhibit < ApplicationRecord
  belongs_to :museum
  has_many :taggings
  has_many :tickets
  has_many :tags, through: :taggings
  accepts_nested_attributes_for :taggings, :allow_destroy => true

  has_attached_file :photo, styles: { large: "768x768>", medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\Z/
  validates_presence_of :name, :start_date, :end_date, :blurb, :description, :photo
  validates_uniqueness_of :name
end

app/models/museum.rb
class Museum < ApplicationRecord
  has_many :tickets
  has_many :taggings
  has_many :tags, through: :taggings
  default_scope { where(active: true) }
  accepts_nested_attributes_for :taggings, :allow_destroy => true
  has_many :exhibits
  has_many :events
  has_many :pieces

  has_attached_file :photo, styles: { large: "768x768>", medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\Z/

  validates_presence_of :name, :blurb, :description, :photo, :price, :address
  validates_uniqueness_of :name

  geocoded_by :address
  after_validation :geocode, if: ->(obj){ obj.address.present? and obj.address_changed? }
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :tickets
  before_save :update_subtotal

  def subtotal
    tickets.collect {|ticket| ticket.valid? ? (ticket.quantity * ticket.unit_price) : 0}.sum
  end

  private

  def update_subtotal
    self[:subtotal] = subtotal
  end

end

app/models/piece.rb
class Piece < ApplicationRecord
  belongs_to :museum
  has_many :taggings
  has_many :tags, through: :taggings
  accepts_nested_attributes_for :taggings, :allow_destroy => true

  has_attached_file :photo, styles: { large: "768x768>", medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\Z/

  validates_presence_of :name, :blurb, :description, :photo
  validates_uniqueness_of :name

end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :taggings, :inverse_of => :tag
  has_many :museums, through: :taggings
  has_many :exhibits, through: :taggings
  has_many :users, through: :taggings
  has_many :pieces, through: :taggings
  has_many :events, through: :taggings


end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :tag, :inverse_of => :taggings, :required => false
  belongs_to :museum, :inverse_of => :taggings, :required => false
  belongs_to :exhibit, :inverse_of => :taggings, :required => false
  belongs_to :event, :inverse_of => :taggings, :required => false
  belongs_to :piece, :inverse_of => :taggings, :required => false
  belongs_to :user, :inverse_of => :taggings, :required => false

end

app/models/ticket.rb
class Ticket < ApplicationRecord
  belongs_to :user
  belongs_to :museum
  belongs_to :exhibit, :required => false
  belongs_to :order

  validates :quantity, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  before_save :finalize

  def unit_price
    if self.exhibit_id != nil
      exhibit.price
    else
      if persisted?
        self[:unit_price]
      else
        museum.price
      end
    end
  end

  def total_price
    unit_price * quantity
  end

  private

  def museum_present
    if museum.nil?
      errors.add(:museum, "is not a valid museum")
    end
  end

  def order_present
    if order.nil?
      errors.add(:order, "is not a valid order.")
    end
  end

  def finalize
    self[:unit_price] = unit_price
    self[:total_price] = quantity * self[:unit_price]
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :tickets
  has_many :taggings, :inverse_of => :user
  has_many :tags, through: :taggings
  accepts_nested_attributes_for :taggings, :allow_destroy => true

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, :omniauth_providers => [:facebook]

end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/exhibit_helper.rb
module ExhibitHelper
end

app/helpers/museum_helper.rb
module MuseumHelper
end

app/helpers/pieces_helper.rb
module PiecesHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/ticket_helper.rb
module TicketHelper

  def total_tickets(museum)
    @total = []
      Ticket.all.where(museum_id: museum.id).each do |ticket|
        @total << ticket.original_quantity
      end
    @total.inject(0, :+)
  end

  def total_redeemed(museum)
    @total = []
      Ticket.all.where(museum_id: museum.id).each do |ticket|
        if ticket.redeemed == true
          @total << ticket.original_quantity
        end
      end
    @total.inject(0, :+)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_cart_text.html.erb
<% if number_to_currency current_order.subtotal != 0.00 %>
  <%= link_to "#{current_order.tickets.size} Items in Cart ( #{number_to_currency current_order.subtotal} )", cart_path(id: current_user.id), class: "btn btn-link" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Medici</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAc7bgkQoYVVLBCkZtxYPzzWCogA-3LmNY&callback=initMap" async defer></script>
    <script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <!-- CDN references -->
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.1.0.min.js" integrity="sha256-cCueBR6CsyA4/9szpPfrX3s49M9vUU5BgtiJj06wt/s=" crossorigin="anonymous"></script>
    <script src="https://unpkg.com/imagesloaded@4.1/imagesloaded.pkgd.js"></script>
    <script src= "https://cdn.jsdelivr.net/masonry/4.1.1/masonry.pkgd.min.js"></script>
    <link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.3/css/font-awesome.min.css">
  </head>

  <body>
    <script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>
    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-3 col-lg-2">
          <nav class="navbar navbar-default navbar-fixed-side">
            <div class="container">
              <div class="navbar-header">
                <button class="navbar-toggle" data-target=".navbar-collapse" data-toggle="collapse">
                  <span class="sr-only">Toggle navigation</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                </button>
                <%= link_to image_tag("Medici_logos/m_logo_simple_grey.jpg"), root_path, class: "navbar-left hidden-xs"%>
                <% if current_user %>
                  <%= link_to "Hi, #{current_user.name}!", current_user, class: "navbar-brand" %>

                <% end %>
              </div>
              <div class="collapse navbar-collapse">
                <div id= "search-wrapper">
                  <%= form_tag(exhibits_search_show_path, :method => "get", id: "search-form") do %>
                    <i class="fa fa-search" aria-hidden="true" style="font-size: 20px"></i>
                    <%= text_field_tag :search, params[:search], placeholder: "Search" %>
                  <% end %>
                  <%= link_to "Advanced Search", exhibits_search_new_path %>
                </div>

                <% if ["index"].include?(params[:action]) %>
                  <label class="checkbox-wrapper" for="museum-toggle">
                    <input type="checkbox" id="museum-toggle" class="hidden" checked>
                    <div class=" well museum-label-toggle"></div>
                    <label for="museum-toggle"><p>museums</p></label>
                  </label>
                  <label class="checkbox-wrapper" for="exhibit-toggle">
                    <input type="checkbox" id="exhibit-toggle" class="hidden" checked>
                    <div class=" well exhibit-label-toggle"></div>
                    <label for="exhibit-toggle"><p>exhibits</p></label>
                  </label>
                  <label class="checkbox-wrapper" for="event-toggle">
                    <input type="checkbox" id="event-toggle" class="hidden" checked>
                    <div class=" well event-label-toggle"></div>
                    <label for="event-toggle"><p>events</p></label>
                  </label>
                <% end %>

                <% if current_user %>
                <button type="button"class="list-group-item">
                  <%= link_to "Checkout", cart_path(current_user.id) %>
                  <span class="glyphicon glyphicon-shopping-cart"></span>
                  <%if current_order.tickets.where(paid: false).size > 0 %>
                    <span class="badge"> <%= "#{current_order.tickets.size}" %> </span>
                  <% end %>
                </button>
                  <%= link_to "Logout", destroy_user_session_path, :method => :delete, class: "list-group-item" %>
                <% else %>
                  <button type="button" class="list-group-item" data-toggle="modal" data-target="#Log-In-Modal">log in</button>
                  <button type="button" class="list-group-item" data-toggle="modal" data-target="#Register-Modal">register</button>
                  <button type="button"class="list-group-item">
                    <a href="#">Check Out</a>
                    <span class="glyphicon glyphicon-shopping-cart"></span>
                    <%if current_order.tickets.where(paid: false).size > 0 %>
                    <span class="badge"> <%= "#{current_order.tickets.size}" %> </span>
                    <% end %>
                  </button>
                <% end %>
              </div>
              <footer class="hidden-xs">
              <%= link_to "https://www.facebook.com/mediciapp" do %>
                <i class="fa fa-facebook-square" aria-hidden="true"></i>
              <% end %>
              <%= link_to "https://www.instagram.com/medici_app/" do %>
                <i class="fa fa-instagram" aria-hidden="true"></i>
              <% end %>
              <%= link_to "https://twitter.com/medici_app" do %>
                <i class="fa fa-twitter-square" aria-hidden="true"></i>
              <% end %>
              <p class= "text-muted">Medici LLC, Is brought to you buy the international asscociation of dislexic court reporters</p>
            </footer>
            </div>
          </nav>
        </div>
        <div id="Log-In-Modal" class="modal fade" role="dialog">
          <div class="modal-dialog">
            <div class="modal-form">
              <%= form_for(resource, as: resource_name, url: session_path(resource_name), class:"modal-body") do |f| %>
                <p class="title">Log in</p>
                <%= f.email_field :email, placeholder:"e-mail", autofocus: true, class:"input-field"%>
                <%= f.password_field :password, placeholder:"password", autocomplete: "off", class:"input-field" %>
                <div class="checkbox">
                  <label><%= f.check_box :remember_me %><p>remember me</p></label>
                </div>
                <%= link_to "Forgot your password?", new_user_password_path %>
                <%= f.submit "Log in", class:"input-button"%>
              <% end %>
            </div>
          </div>
        </div>
        <div id="Register-Modal" class="modal fade" role="dialog">
          <div class="modal-dialog">
            <div class="modal-form">
              <%= devise_error_messages! %>
              <%= form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
                <p class="title">sign up</p>
                <%= f.text_field :name, placeholder:"name", autofocus: true, class:"input-field" %>
                <%= f.email_field :email, placeholder:"e-mail", class:"input-field"%>
                <div class="field">
                  <% if @minimum_password_length %>
                  <em>(<%= @minimum_password_length %> characters minimum)</em>
                  <% end %>
                  <%= f.password_field :password, placeholder: "password", autocomplete: "off", class:"input-field" %>
                </div>
                  <%= f.password_field :password_confirmation, placeholder: "confirm password", autocomplete: "off", class:"input-field" %>
                <%= f.submit "Log in", class:"input-button"%>
              <% end %>

            </div>
          </div>
        </div>
          <div class="col-sm-9 col-lg-10 content">
            <%= yield %>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>